### ISSUE TITLE
Add ability to locate SMB powerups

### ISSUE THREAD

**Issue by jbeemster** [NES-NN/NES-NN-Testbed#7]

**Comment by ACoderLife** [comment]
Looks like the location of a powerup after it is freed from it's box is located here:
0x04C4 | Powerup hitbox (1x4 bytes, <<x1,y1> <x2,y2>>)
https://datacrystal.romhacking.net/wiki/Super_Mario_Bros.:RAM_map

**Comment by ACoderLife** [comment]
Mapping worked.
I now need to pass into the input grid as 2 or -2

**Comment by ACoderLife** [comment]
Done:
https://github.com/NES-NN/NES-NN-Testbed/tree/feature/GameMemoryMapper
